test_data = [{"text": "cheese and smelly",
              "spans": [{'start': 0, 'end': 6, 'token_start': 0, 'token_end': 4, 'label': 'Population'},
                        {'start': 12, 'end': 17, 'token_start': 11, 'token_end': 15, 'label': 'Demographics'}]},
             {"text": "yes Cheese smelly Cheese smelly",
              "spans": [{'start': 5, 'end': 10, 'token_start': 11, 'token_end': 16, 'label': 'Demographics'},
                        {'start': 12, 'end': 17, 'token_start': 0, 'token_end': 4, 'label': 'Population'},
                        {'start': 18, 'end': 23, 'token_start': 0, 'token_end': 4, 'label': 'Population'},
                        {'start': 24, 'end': 29, 'token_start': 0, 'token_end': 4, 'label': 'Demographics'}]},
             {"text": "Cheese fxb smelly",
              "spans": [{'start': 0, 'end': 6, 'token_start': 0, 'token_end': 4, 'label': 'Demographics'},
                        {'start': 12, 'end': 17, 'token_start': 11, 'token_end': 15, 'label': 'Population'}]},
             {"text": "Cheese fxa smelly", "spans": []},
             {"text": "yes Cheese smelly yes",
              "spans": [{'start': 5, 'end': 10, 'token_start': 11, 'token_end': 16, 'label': 'Population'},
                        {'start': 12, 'end': 17, 'token_start': 0, 'token_end': 4, 'label': 'Demographics'}]},
             ]
